version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
  jobs:
    post_create_environment:
      - pip install -r requirements_dev.txt
      - pip install sphinx

sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub